# Generated by Django 4.1 on 2023-06-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_doctors_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name of the service'),
        ),
        migrations.AlterField(
            model_name='servicescategories',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of the category of the service'),
        ),
    ]
