# Generated by Django 4.1 on 2023-06-04 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_services_name_alter_servicescategories_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Patient Unique ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('confirm_password', models.CharField(max_length=100, verbose_name='Confirm Password')),
                ('contact_number', models.CharField(max_length=13, verbose_name='Contact number (optional)')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of birth (optional)')),
                ('profile_picture', models.ImageField(upload_to='patients-profile-pictures', verbose_name='Profile picture')),
                ('address1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 1 (optional)')),
                ('address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2 (optional)')),
                ('country', models.CharField(blank=True, choices=[('UZ', 'Uzbekistan'), ('KR', 'Karakalpakistan'), ('KZ', 'Kazakhstan'), ('RU', 'Russia')], max_length=50, null=True, verbose_name='Country (optional)')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State (optional)')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City (optional)')),
                ('postal_code', models.IntegerField(blank=True, null=True, verbose_name='Postal Code (optional)')),
            ],
        ),
    ]
