# Generated by Django 4.1 on 2023-06-03 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'names',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_number', models.IntegerField(blank=True, max_length=12, null=True, verbose_name='Contact Number')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('confirm_password', models.CharField(max_length=20, verbose_name='Confirm Password')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('experience_in_year', models.IntegerField(blank=True, null=True, verbose_name='Experience In Year')),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female')], max_length=50, verbose_name='Gender')),
                ('profile_picture', models.ImageField(upload_to='doctors-profile-pictures', verbose_name='Profile picture')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('address1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2')),
                ('country', models.CharField(blank=True, choices=[('UZ', 'Uzbekistan'), ('KR', 'Karakalpakistan'), ('KZ', 'Kazakhstan'), ('RU', 'Russia')], max_length=50, null=True, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('postal_code', models.IntegerField(blank=True, null=True, verbose_name='Postal Code')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.specializations')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
            },
        ),
    ]
