# Generated by Django 4.1 on 2023-06-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specializations',
            options={'verbose_name': 'specialization', 'verbose_name_plural': 'specializations'},
        ),
        migrations.AddField(
            model_name='doctors',
            name='friday',
            field=models.BooleanField(default=False, verbose_name='Friday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='monday',
            field=models.BooleanField(default=False, verbose_name='Monday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='Saturday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='Sunday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name='Thursday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name='Tuesday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name='Wednesday'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contact Number'),
        ),
    ]
