# Generated by Django 4.1 on 2023-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_servicescategories_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='address1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 1 (optional)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='address2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2 (optional)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City (optional)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Contact Number (optional)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='country',
            field=models.CharField(blank=True, choices=[('UZ', 'Uzbekistan'), ('KR', 'Karakalpakistan'), ('KZ', 'Kazakhstan'), ('RU', 'Russia')], max_length=50, null=True, verbose_name='Country (optional)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth (optional)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='experience_in_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Experience in Year (optional)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Postal Code (optional)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State (optional)'),
        ),
    ]
