# Generated by Django 4.1 on 2023-06-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffsRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff Role')),
            ],
            options={
                'verbose_name': 'staffs role',
                'verbose_name_plural': 'staffs roles',
            },
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
        migrations.AlterField(
            model_name='patients',
            name='confirm_password',
            field=models.CharField(max_length=20, verbose_name='Confirm Password'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Password'),
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Visit Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description (optional)')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Contact Number (optional)')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='Password')),
                ('confirm_password', models.CharField(blank=True, max_length=20, null=True, verbose_name='Confirm Pasword')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='Gender')),
                ('profile_picture', models.ImageField(upload_to='staffs-profile-pictures', verbose_name='Profile picture')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.staffsroles')),
            ],
            options={
                'verbose_name': 'sraff',
                'verbose_name_plural': 'staffs',
            },
        ),
    ]
