# Generated by Django 4.1 on 2023-06-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_staffsroles_alter_patients_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visits',
            options={'verbose_name': 'visit', 'verbose_name_plural': 'visits'},
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='wednesday',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='country',
            field=models.CharField(blank=True, choices=[('Uzbekistan', 'Uzbekistan'), ('Karakalpakistan', 'Karakalpakistan'), ('Kazakhstan', 'Kazakhstan'), ('Russia', 'Russia')], max_length=50, null=True, verbose_name='Country (optional)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='experience_in_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Experience in Year (optional)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Postal Code (optional)'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Postal Code (optional)'),
        ),
    ]
