# Generated by Django 4.1 on 2023-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_visits_options_remove_doctors_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='friday',
            field=models.BooleanField(default=False, verbose_name='Friday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='monday',
            field=models.BooleanField(default=False, verbose_name='Monday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='Saturday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='Sunday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name='Thursday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name='Tuesday'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name='Wednesday'),
        ),
    ]
